.TH "dcrudLocalFactory_s" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcrudLocalFactory_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IParticipant\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "dcrudClassID \fBclassID\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "\fBdcrudLocalFactory_Initialize\fP \fBinitialize\fP"
.br
.ti -1c
.RI "\fBdcrudLocalFactory_Set\fP \fBset\fP"
.br
.ti -1c
.RI "\fBdcrudLocalFactory_Serialize\fP \fBserialize\fP"
.br
.ti -1c
.RI "\fBdcrudLocalFactory_Unserialize\fP \fBunserialize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file IParticipant\&.h\&.
.SH "Field Documentation"
.PP 
.SS "dcrudClassID classID"

.PP
Definition at line 26 of file IParticipant\&.h\&.
.SS "\fBdcrudLocalFactory_Initialize\fP initialize"

.PP
Definition at line 28 of file IParticipant\&.h\&.
.SS "\fBdcrudLocalFactory_Serialize\fP serialize"

.PP
Definition at line 30 of file IParticipant\&.h\&.
.SS "\fBdcrudLocalFactory_Set\fP set"

.PP
Definition at line 29 of file IParticipant\&.h\&.
.SS "size_t size"

.PP
Definition at line 27 of file IParticipant\&.h\&.
.SS "\fBdcrudLocalFactory_Unserialize\fP unserialize"

.PP
Definition at line 31 of file IParticipant\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
