.TH "dcrudRemoteFactory_s" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcrudRemoteFactory_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IParticipant\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "dcrudClassID \fBclassID\fP"
.br
.ti -1c
.RI "void * \fBuserContext\fP"
.br
.ti -1c
.RI "dcrudIParticipant \fBparticipant\fP"
.br
.ti -1c
.RI "\fBdcrudRemoteFactory_create\fP \fBcreate\fP"
.br
.ti -1c
.RI "\fBdcrudRemoteFactory_update\fP \fBupdate\fP"
.br
.ti -1c
.RI "\fBdcrudRemoteFactory_delete\fP \fBdelete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 35 of file IParticipant\&.h\&.
.SH "Field Documentation"
.PP 
.SS "dcrudClassID classID"

.PP
Definition at line 37 of file IParticipant\&.h\&.
.SS "\fBdcrudRemoteFactory_create\fP create"

.PP
Definition at line 40 of file IParticipant\&.h\&.
.SS "\fBdcrudRemoteFactory_delete\fP delete"

.PP
Definition at line 42 of file IParticipant\&.h\&.
.SS "dcrudIParticipant participant"

.PP
Definition at line 39 of file IParticipant\&.h\&.
.SS "\fBdcrudRemoteFactory_update\fP update"

.PP
Definition at line 41 of file IParticipant\&.h\&.
.SS "void* userContext"

.PP
Definition at line 38 of file IParticipant\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
