.TH "inc/dcrud/ICRUD.h" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/ICRUD.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Shareable\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudICRUD)"
.br
.ti -1c
.RI "void \fBdcrudICRUD_create\fP (dcrudICRUD This, dcrudArguments how)"
.br
.ti -1c
.RI "void \fBdcrudICRUD_update\fP (dcrudICRUD This, dcrudShareable what, dcrudArguments how)"
.br
.ti -1c
.RI "void \fBdcrudICRUD_delete\fP (dcrudICRUD This, dcrudShareable what)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dcrudICRUD_create (dcrudICRUDThis, dcrudArgumentshow)"

.SS "void dcrudICRUD_delete (dcrudICRUDThis, dcrudShareablewhat)"

.SS "void dcrudICRUD_update (dcrudICRUDThis, dcrudShareablewhat, dcrudArgumentshow)"

.SS "UTIL_ADT (dcrudICRUD)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
