.TH "ioInetSocketAddress_s" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ioInetSocketAddress_s \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InetSocketAddress\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBinetAddress\fP [16]"
.br
.ti -1c
.RI "unsigned short \fBport\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file InetSocketAddress\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char inetAddress[16]"

.PP
Definition at line 8 of file InetSocketAddress\&.h\&.
.SS "unsigned short port"

.PP
Definition at line 9 of file InetSocketAddress\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
