.TH "inc/dcrud/IParticipant.h" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IParticipant.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <io/InetSocketAddress\&.h>\fP
.br
\fC#include 'ICache\&.h'\fP
.br
\fC#include 'IDispatcher\&.h'\fP
.br
\fC#include 'IRegistry\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdcrudLocalFactory_s\fP"
.br
.ti -1c
.RI "struct \fBdcrudRemoteFactory_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef dcrudShareable(* \fBdcrudShareableFactory\fP )()"
.br
.ti -1c
.RI "typedef void(* \fBdcrudLocalFactory_Set\fP )(\fBdcrudShareableData\fP This, const \fBdcrudShareableData\fP source)"
.br
.ti -1c
.RI "typedef \fBioStatus\fP(* \fBdcrudLocalFactory_Serialize\fP )(\fBdcrudShareableData\fP This, ioByteBuffer target)"
.br
.ti -1c
.RI "typedef \fBioStatus\fP(* \fBdcrudLocalFactory_Unserialize\fP )(\fBdcrudShareableData\fP This, ioByteBuffer source)"
.br
.ti -1c
.RI "typedef \fBbool\fP(* \fBdcrudLocalFactory_Initialize\fP )(\fBdcrudShareableData\fP This)"
.br
.ti -1c
.RI "typedef void(* \fBdcrudRemoteFactory_create\fP )(struct \fBdcrudRemoteFactory_s\fP *This, dcrudArguments how)"
.br
.ti -1c
.RI "typedef void(* \fBdcrudRemoteFactory_update\fP )(struct \fBdcrudRemoteFactory_s\fP *This, dcrudShareable what, dcrudArguments how)"
.br
.ti -1c
.RI "typedef void(* \fBdcrudRemoteFactory_delete\fP )(struct \fBdcrudRemoteFactory_s\fP *This, dcrudShareable what)"
.br
.ti -1c
.RI "typedef struct \fBdcrudLocalFactory_s\fP \fBdcrudLocalFactory\fP"
.br
.ti -1c
.RI "typedef struct \fBdcrudRemoteFactory_s\fP \fBdcrudRemoteFactory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBUTIL_ADT\fP (dcrudIParticipant)"
.br
.ti -1c
.RI "void \fBdcrudIParticipant_listen\fP (dcrudIParticipant This, dcrudIRegistry registry, const char *intrfc, \fBbool\fP dumpReceivedBuffer)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIParticipant_registerLocalFactory\fP (dcrudIParticipant This, \fBdcrudLocalFactory\fP *local)"
.br
.ti -1c
.RI "\fBbool\fP \fBdcrudIParticipant_registerRemoteFactory\fP (dcrudIParticipant This, \fBdcrudRemoteFactory\fP *remote)"
.br
.ti -1c
.RI "dcrudICache \fBdcrudIParticipant_getDefaultCache\fP (dcrudIParticipant This)"
.br
.ti -1c
.RI "\fBdcrudStatus\fP \fBdcrudIParticipant_createCache\fP (dcrudIParticipant This, dcrudICache *target, \fBbyte\fP *cacheId)"
.br
.ti -1c
.RI "dcrudICache \fBdcrudIParticipant_getCache\fP (dcrudIParticipant This, \fBbyte\fP ID)"
.br
.ti -1c
.RI "dcrudIDispatcher \fBdcrudIParticipant_getDispatcher\fP (dcrudIParticipant This)"
.br
.ti -1c
.RI "dcrudShareable \fBdcrudIParticipant_createShareable\fP (dcrudIParticipant This, dcrudClassID classID)"
.br
.ti -1c
.RI "void \fBdcrudIParticipant_run\fP (dcrudIParticipant This)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBdcrudLocalFactory_s\fP  \fBdcrudLocalFactory\fP"

.SS "typedef \fBbool\fP(*  dcrudLocalFactory_Initialize)(\fBdcrudShareableData\fP This)"

.PP
Definition at line 18 of file IParticipant\&.h\&.
.SS "typedef \fBioStatus\fP(*  dcrudLocalFactory_Serialize)(\fBdcrudShareableData\fP This, ioByteBuffer target)"

.PP
Definition at line 16 of file IParticipant\&.h\&.
.SS "typedef void(*  dcrudLocalFactory_Set)(\fBdcrudShareableData\fP This, const \fBdcrudShareableData\fP source)"

.PP
Definition at line 15 of file IParticipant\&.h\&.
.SS "typedef \fBioStatus\fP(*  dcrudLocalFactory_Unserialize)(\fBdcrudShareableData\fP This, ioByteBuffer source)"

.PP
Definition at line 17 of file IParticipant\&.h\&.
.SS "typedef struct \fBdcrudRemoteFactory_s\fP  \fBdcrudRemoteFactory\fP"

.SS "typedef void(*  dcrudRemoteFactory_create)(struct \fBdcrudRemoteFactory_s\fP *This, dcrudArguments how)"

.PP
Definition at line 20 of file IParticipant\&.h\&.
.SS "typedef void(*  dcrudRemoteFactory_delete)(struct \fBdcrudRemoteFactory_s\fP *This, dcrudShareable what)"

.PP
Definition at line 22 of file IParticipant\&.h\&.
.SS "typedef void(*  dcrudRemoteFactory_update)(struct \fBdcrudRemoteFactory_s\fP *This, dcrudShareable what, dcrudArguments how)"

.PP
Definition at line 21 of file IParticipant\&.h\&.
.SS "typedef dcrudShareable(*  dcrudShareableFactory)()"

.PP
Definition at line 11 of file IParticipant\&.h\&.
.SH "Function Documentation"
.PP 
.SS "\fBdcrudStatus\fP dcrudIParticipant_createCache (dcrudIParticipantThis, dcrudICache *target, \fBbyte\fP *cacheId)"

.SS "dcrudShareable dcrudIParticipant_createShareable (dcrudIParticipantThis, dcrudClassIDclassID)"

.SS "dcrudICache dcrudIParticipant_getCache (dcrudIParticipantThis, \fBbyte\fPID)"

.SS "dcrudICache dcrudIParticipant_getDefaultCache (dcrudIParticipantThis)"

.SS "dcrudIDispatcher dcrudIParticipant_getDispatcher (dcrudIParticipantThis)"

.SS "void dcrudIParticipant_listen (dcrudIParticipantThis, dcrudIRegistryregistry, const char *intrfc, \fBbool\fPdumpReceivedBuffer)"
Use the registry to instanciate and listen to other participants\&. 
.PP
\fBParameters:\fP
.RS 4
\fIThis\fP this participant 
.br
\fIregistry\fP the registry to use 
.br
\fIintrfc\fP the network interface to use, identified by its IP address, may be null, in such case the first up, non loopback, multicast capable interface will be used 
.br
\fIdumpReceivedBuffer\fP if true, dump the received frames on stderr 
.RE
.PP

.SS "\fBbool\fP dcrudIParticipant_registerLocalFactory (dcrudIParticipantThis, \fBdcrudLocalFactory\fP *local)"

.SS "\fBbool\fP dcrudIParticipant_registerRemoteFactory (dcrudIParticipantThis, \fBdcrudRemoteFactory\fP *remote)"

.SS "void dcrudIParticipant_run (dcrudIParticipantThis)"

.SS "UTIL_ADT (dcrudIParticipant)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
