.TH "inc/dcrud/Network.h" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/Network.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dcrud/IParticipant\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "dcrudIParticipant \fBdcrudNetwork_join\fP (unsigned int id, const \fBioInetSocketAddress\fP *addr, const char *intrfc)"
.br
.ti -1c
.RI "void \fBdcrudNetwork_leave\fP (dcrudIParticipant *participant)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "dcrudIParticipant dcrudNetwork_join (unsigned intid, const \fBioInetSocketAddress\fP *addr, const char *intrfc)"

.PP
\fBParameters:\fP
.RS 4
\fIid\fP participant id 
.br
\fIaddr\fP IP address:port pair 
.br
\fIintrfc\fP the network interface to use, identified by its IP address, may be null in such case the first up, non loopback, multicast capable interface will be used) 
.RE
.PP

.SS "void dcrudNetwork_leave (dcrudIParticipant *participant)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
