.TH "inc/dcrud/Network.h" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/Network.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dcrud/IParticipant\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "dcrudIParticipant \fBdcrudNetwork_join\fP (unsigned int publisherId, const char *mcastAddr, unsigned short port, const char *intrfc, \fBbool\fP dumpReceivedBuffer)"
.br
.ti -1c
.RI "void \fBdcrudNetwork_leave\fP (dcrudIParticipant *participant)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "dcrudIParticipant dcrudNetwork_join (unsigned intpublisherId, const char *mcastAddr, unsigned shortport, const char *intrfc, \fBbool\fPdumpReceivedBuffer)"

.SS "void dcrudNetwork_leave (dcrudIParticipant *participant)"

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
