.TH "inc/io/ByteBuffer.hpp" 3 "Mon Dec 14 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/io/ByteBuffer.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br
\fC#include <io/ByteBuffer\&.h>\fP
.br
\fC#include <io/socket\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBByteBuffer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBio\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBByteOrder\fP { \fBioByteOrder_BIG_ENDIAN\fP, \fBioByteOrder_LITTLE_ENDIAN\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
