.TH "ICRUD" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICRUD \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ICRUD\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~ICRUD\fP (void)"
.br
.ti -1c
.RI "virtual void \fBcreate\fP (const \fBArguments\fP &how)=0"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (\fBShareable\fP &what, const \fBArguments\fP &how)=0"
.br
.ti -1c
.RI "virtual void \fBdeleTe\fP (\fBShareable\fP &what)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file ICRUD\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBICRUD\fP (void)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 10 of file ICRUD\&.hpp\&.
.PP
.nf
10 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void create (const \fBArguments\fP &how)\fC [pure virtual]\fP"

.SS "virtual void deleTe (\fBShareable\fP &what)\fC [pure virtual]\fP"

.SS "virtual void update (\fBShareable\fP &what, const \fBArguments\fP &how)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
