.TH "Network" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIParticipant\fP & \fBjoin\fP (unsigned int id, const \fBio::InetSocketAddress\fP &addr, const std::string &intrfc)"
.br
.ti -1c
.RI "static \fBIParticipant\fP & \fBjoin\fP (unsigned int id, const \fBio::InetSocketAddress\fP &addr)"
.br
.ti -1c
.RI "static void \fBleave\fP (\fBIParticipant\fP &participant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Network\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIParticipant\fP& join (unsigned intid, const \fBio::InetSocketAddress\fP &addr, const std::string &intrfc)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIid\fP participant id 
.br
\fIaddr\fP IP address:port pair 
.br
\fIintrfc\fP the network interface to use, identified by its IP address 
.RE
.PP

.SS "static \fBIParticipant\fP& join (unsigned intid, const \fBio::InetSocketAddress\fP &addr)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fIid\fP participant id 
.br
\fIaddr\fP IP address:port pair \fINote\fP: The first up, non loopback, multicast capable interface will be used 
.RE
.PP

.SS "static void leave (\fBIParticipant\fP &participant)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
