.TH "GUID" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GUID \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GUID\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGUID\fP ()"
.br
.ti -1c
.RI "\fBGUID\fP (const \fBGUID\fP &right)"
.br
.ti -1c
.RI "\fBGUID\fP & \fBoperator=\fP (const \fBGUID\fP &right)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBGUID\fP &right) const "
.br
.ti -1c
.RI "bool \fBisShared\fP () const "
.br
.ti -1c
.RI "int \fBcompareTo\fP (const \fBGUID\fP &right) const "
.br
.ti -1c
.RI "void \fBset\fP (const \fBGUID\fP &id)"
.br
.ti -1c
.RI "void \fBserialize\fP (\fBio::ByteBuffer\fP &buffer) const "
.br
.ti -1c
.RI "std::string \fBtoString\fP (void) const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGUID\fP \fBunserialize\fP (\fBio::ByteBuffer\fP &buffer)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const unsigned int \fBSIZE\fP = 4 + 4"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCache\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file GUID\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGUID\fP ()\fC [inline]\fP"

.PP
Definition at line 18 of file GUID\&.hpp\&.
.PP
.nf
18              :
19          _publisher( 0 ),
20          _instance ( 0 )
21       {}
.fi
.SS "\fBGUID\fP (const \fBGUID\fP &right)\fC [inline]\fP"

.PP
Definition at line 23 of file GUID\&.hpp\&.
.PP
.nf
23                                  :
24          _publisher( right\&._publisher ),
25          _instance ( right\&._instance  )
26       {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "int compareTo (const \fBGUID\fP &right) const"

.SS "bool isShared () const\fC [inline]\fP"

.PP
Definition at line 38 of file GUID\&.hpp\&.
.PP
.nf
38                             {
39          return _instance != 0;
40       }
.fi
.SS "bool operator< (const \fBGUID\fP &right) const\fC [inline]\fP"

.PP
Definition at line 34 of file GUID\&.hpp\&.
.PP
.nf
34                                                    {
35          return compareTo( right ) < 0;
36       }
.fi
.SS "\fBGUID\fP& operator= (const \fBGUID\fP &right)\fC [inline]\fP"

.PP
Definition at line 28 of file GUID\&.hpp\&.
.PP
.nf
28                                                {
29          _publisher = right\&._publisher;
30          _instance  = right\&._instance;
31          return *this;
32       }
.fi
.SS "void serialize (\fBio::ByteBuffer\fP &buffer) const"

.SS "void set (const \fBGUID\fP &id)"

.SS "std::string toString (void) const"

.SS "static \fBGUID\fP unserialize (\fBio::ByteBuffer\fP &buffer)\fC [static]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class Cache\fC [friend]\fP"

.PP
Definition at line 55 of file GUID\&.hpp\&.
.SH "Field Documentation"
.PP 
.SS "const unsigned int SIZE = 4 + 4\fC [static]\fP"

.PP
Definition at line 14 of file GUID\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
