.TH "Network" 3 "Mon Dec 14 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIParticipant\fP & \fBjoin\fP (const char *networkConfFile, const char *intrfcName, unsigned short id)"
.br
.ti -1c
.RI "static void \fBleave\fP (\fBIParticipant\fP &toDelete)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file Network\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIParticipant\fP& join (const char *networkConfFile, const char *intrfcName, unsigned shortid)\fC [static]\fP"

.SS "static void leave (\fBIParticipant\fP &toDelete)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
