.TH "IProvided" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IProvided \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IProvided\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IProvided\fP ()"
.br
.ti -1c
.RI "virtual \fBIProvided\fP & \fBaddOperation\fP (const std::string &operationName, \fBIOperation\fP &executor)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file IProvided\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBIProvided\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 12 of file IProvided\&.hpp\&.
.PP
.nf
12 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBIProvided\fP& addOperation (const std::string &operationName, \fBIOperation\fP &executor)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
