.TH "IOperation" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IOperation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IOperation\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~IOperation\fP ()"
.br
.ti -1c
.RI "virtual \fBArguments\fP * \fBexecute\fP (\fBIParticipant\fP &participant, const \fBArguments\fP &args)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file IOperation\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual ~\fBIOperation\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 12 of file IOperation\&.hpp\&.
.PP
.nf
12 {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBArguments\fP* execute (\fBIParticipant\fP &participant, const \fBArguments\fP &args)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
