.TH "dcrud" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcrud \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBArguments\fP"
.br
.ti -1c
.RI "class \fBClassID\fP"
.br
.ti -1c
.RI "class \fBGUID\fP"
.br
.ti -1c
.RI "class \fBICache\fP"
.br
.ti -1c
.RI "class \fBICallback\fP"
.br
.ti -1c
.RI "class \fBICRUD\fP"
.br
.ti -1c
.RI "class \fBIDispatcher\fP"
.br
.ti -1c
.RI "class \fBIOperation\fP"
.br
.ti -1c
.RI "class \fBIParticipant\fP"
.br
.ti -1c
.RI "class \fBIProvided\fP"
.br
.ti -1c
.RI "class \fBIRequired\fP"
.br
.ti -1c
.RI "class \fBNetwork\fP"
.br
.ti -1c
.RI "class \fBShareable\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef bool(* \fBshareablePredicate_t\fP )(const \fBShareable\fP &shareable)"
.br
.ti -1c
.RI "typedef std::set< \fBShareable\fP * > \fBshareables_t\fP"
.br
.ti -1c
.RI "typedef shareables_t::iterator \fBshareablesIter_t\fP"
.br
.ti -1c
.RI "typedef \fBShareable\fP *(* \fBlocalFactory_t\fP )(void)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBNO_ERROR\fP, \fBALREADY_CREATED\fP, \fBNOT_OWNER\fP, \fBNOT_CREATED\fP, \fBNOT_IN_THIS_CACHE\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBShareable\fP*(*  localFactory_t)(void)"

.PP
Definition at line 14 of file IParticipant\&.hpp\&.
.SS "typedef bool( *  shareablePredicate_t)(const \fBShareable\fP &shareable)"

.PP
Definition at line 14 of file ICache\&.hpp\&.
.SS "typedef std::set<\fBShareable\fP *> \fBshareables_t\fP"

.PP
Definition at line 16 of file ICache\&.hpp\&.
.SS "typedef shareables_t::iterator \fBshareablesIter_t\fP"

.PP
Definition at line 17 of file ICache\&.hpp\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBStatus\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINO_ERROR \fP\fP
.TP
\fB\fIALREADY_CREATED \fP\fP
.TP
\fB\fINOT_OWNER \fP\fP
.TP
\fB\fINOT_CREATED \fP\fP
.TP
\fB\fINOT_IN_THIS_CACHE \fP\fP
.PP
Definition at line 9 of file Status\&.hpp\&.
.PP
.nf
9                {
10 
11       NO_ERROR,
12       ALREADY_CREATED,
13       NOT_OWNER,
14       NOT_CREATED,
15       NOT_IN_THIS_CACHE
16    };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
