.TH "Arguments" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arguments \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Arguments\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArguments\fP (void)"
.br
.ti -1c
.RI "\fB~Arguments\fP ()"
.br
.ti -1c
.RI "void \fBclear\fP ()"
.br
.ti -1c
.RI "bool \fBisEmpty\fP () const "
.br
.ti -1c
.RI "size_t \fBgetCount\fP () const "
.br
.ti -1c
.RI "void \fBputNull\fP (const std::string &key)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const byte &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const bool &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const unsigned short &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const unsigned int &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const uint64_t &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const float &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const double &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const std::string &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const \fBClassID\fP &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const \fBGUID\fP &value)"
.br
.ti -1c
.RI "void \fBput\fP (const std::string &key, const \fBShareable\fP *value)"
.br
.ti -1c
.RI "bool \fBisNull\fP (const std::string &key) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, byte &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, bool &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, unsigned short &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, unsigned int &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, uint64_t &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, float &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, double &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, std::string &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, \fBClassID\fP &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, \fBGUID\fP &value) const "
.br
.ti -1c
.RI "bool \fBget\fP (const std::string &key, \fBShareable\fP *&value) const "
.br
.ti -1c
.RI "void \fBsetMode\fP (byte mode)"
.br
.ti -1c
.RI "void \fBsetQueue\fP (byte queue)"
.br
.ti -1c
.RI "\fBClassID::Type\fP \fBgetType\fP (const std::string &key) const "
.br
.ti -1c
.RI "void \fBserialize\fP (\fBio::ByteBuffer\fP &message) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Arguments\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBArguments\fP (void)"

.SS "~\fBArguments\fP ()"

.SH "Member Function Documentation"
.PP 
.SS "void clear ()"

.SS "bool get (const std::string &key, byte &value) const"

.SS "bool get (const std::string &key, bool &value) const"

.SS "bool get (const std::string &key, unsigned short &value) const"

.SS "bool get (const std::string &key, unsigned int &value) const"

.SS "bool get (const std::string &key, uint64_t &value) const"

.SS "bool get (const std::string &key, float &value) const"

.SS "bool get (const std::string &key, double &value) const"

.SS "bool get (const std::string &key, std::string &value) const"

.SS "bool get (const std::string &key, \fBClassID\fP &value) const"

.SS "bool get (const std::string &key, \fBGUID\fP &value) const"

.SS "bool get (const std::string &key, \fBShareable\fP *&value) const"

.SS "size_t getCount () const\fC [inline]\fP"

.PP
Definition at line 28 of file Arguments\&.hpp\&.
.PP
.nf
28                               {
29          return _args\&.size();
30       }
.fi
.SS "\fBClassID::Type\fP getType (const std::string &key) const"

.SS "bool isEmpty () const\fC [inline]\fP"

.PP
Definition at line 24 of file Arguments\&.hpp\&.
.PP
.nf
24                            {
25          return _args\&.empty();
26       }
.fi
.SS "bool isNull (const std::string &key) const"

.SS "void put (const std::string &key, const byte &value)"

.SS "void put (const std::string &key, const bool &value)"

.SS "void put (const std::string &key, const unsigned short &value)"

.SS "void put (const std::string &key, const unsigned int &value)"

.SS "void put (const std::string &key, const uint64_t &value)"

.SS "void put (const std::string &key, const float &value)"

.SS "void put (const std::string &key, const double &value)"

.SS "void put (const std::string &key, const std::string &value)"

.SS "void put (const std::string &key, const \fBClassID\fP &value)"

.SS "void put (const std::string &key, const \fBGUID\fP &value)"

.SS "void put (const std::string &key, const \fBShareable\fP *value)"

.SS "void putNull (const std::string &key)"

.SS "void serialize (\fBio::ByteBuffer\fP &message) const"

.SS "void setMode (bytemode)"

.SS "void setQueue (bytequeue)"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
