.TH "Network" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Network \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Network\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIParticipant\fP & \fBjoin\fP (unsigned int publisherId, const std::string &mcastAddr, unsigned short port, const std::string &intrfc)"
.br
.ti -1c
.RI "static void \fBleave\fP (\fBIParticipant\fP &participant)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Network\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBIParticipant\fP& join (unsigned intpublisherId, const std::string &mcastAddr, unsigned shortport, const std::string &intrfc)\fC [static]\fP"

.SS "static void leave (\fBIParticipant\fP &participant)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
