.TH "io" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBByteBuffer\fP"
.br
.ti -1c
.RI "struct \fBInetSocketAddress\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBByteOrder\fP { \fBioByteOrder_BIG_ENDIAN\fP, \fBioByteOrder_LITTLE_ENDIAN\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBio::InetSocketAddress\fP &left, const \fBio::InetSocketAddress\fP &right)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBByteOrder\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIioByteOrder_BIG_ENDIAN \fP\fP
.TP
\fB\fIioByteOrder_LITTLE_ENDIAN \fP\fP
.PP
Definition at line 14 of file ByteBuffer\&.hpp\&.
.PP
.nf
14                   {
15 
16       ioByteOrder_BIG_ENDIAN,
17       ioByteOrder_LITTLE_ENDIAN
18    };
.fi
.SH "Function Documentation"
.PP 
.SS "bool io::operator< (const \fBio::InetSocketAddress\fP &left, const \fBio::InetSocketAddress\fP &right)\fC [inline]\fP"

.PP
Definition at line 18 of file InetSocketAddress\&.hpp\&.
.PP
.nf
18                                                                                                   {
19       bool lt = left\&._inetAddress < right\&._inetAddress;
20       if( lt ) {
21          return true;
22       }
23       bool gt = left\&._inetAddress > right\&._inetAddress;
24       if( gt ) {
25          return false;
26       }
27       lt = left\&._port < right\&._port;
28       return lt;
29    }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
