.TH "InetSocketAddress" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InetSocketAddress \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InetSocketAddress\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInetSocketAddress\fP (const std::string &host, unsigned short port)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::string \fB_inetAddress\fP"
.br
.ti -1c
.RI "unsigned short \fB_port\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file InetSocketAddress\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBInetSocketAddress\fP (const std::string &host, unsigned shortport)\fC [inline]\fP"

.PP
Definition at line 12 of file InetSocketAddress\&.hpp\&.
.PP
.nf
12                                                                        :
13          _inetAddress( host ),
14          _port       ( port )
15       {}
.fi
.SH "Field Documentation"
.PP 
.SS "std::string _inetAddress"

.PP
Definition at line 9 of file InetSocketAddress\&.hpp\&.
.SS "unsigned short _port"

.PP
Definition at line 10 of file InetSocketAddress\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
