.TH "inc/dcrud/IOperation.hpp" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IOperation.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arguments\&.hpp'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIOperation\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdcrud\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
