.TH "inc/dcrud/IParticipant.hpp" 3 "Mon Dec 14 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IParticipant.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <util/types\&.h>\fP
.br
\fC#include <functional>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBIParticipant\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdcrud\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef Shareable *(* \fBfactory_t\fP )(void)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
