.TH "inc/dcrud/IRegistry.hpp" 3 "Sun Jan 10 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/IRegistry.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <io/InetSocketAddress\&.hpp>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBIRegistry\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdcrud\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::set
.br
< \fBio::InetSocketAddress\fP > \fBsocketAddresses_t\fP"
.br
.ti -1c
.RI "typedef 
.br
socketAddresses_t::const_iterator \fBsocketAddressesCstIter_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
