.TH "Synchronized" 3 "Sat Jan 9 2016" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Synchronized \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Mutex\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSynchronized\fP (\fBMutex\fP &mutex)"
.br
.ti -1c
.RI "\fB~Synchronized\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 36 of file Mutex\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSynchronized\fP (\fBMutex\fP &mutex)\fC [inline]\fP"

.PP
Definition at line 39 of file Mutex\&.hpp\&.
.PP
.nf
39                                     :
40          _mutex( mutex )
41       {
42          _mutex\&.take();
43       }
.fi
.SS "~\fBSynchronized\fP ()\fC [inline]\fP"

.PP
Definition at line 45 of file Mutex\&.hpp\&.
.PP
.nf
45                        {
46          _mutex\&.release();
47       }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
