.TH "inc/dcrud/Status.hpp" 3 "Mon Dec 14 2015" "Version 0.0.0" "dcrud" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/dcrud/Status.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdcrud\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBStatus\fP { \fBNO_ERROR\fP, \fBALREADY_CREATED\fP, \fBNOT_OWNER\fP, \fBNOT_CREATED\fP, \fBNOT_IN_THIS_CACHE\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for dcrud from the source code\&.
